version: '3'

vars:
  VENV_BIN_DIR: venv/bin
  PIP: '{{.VENV_BIN_DIR}}/pip'
  PYTHON: '{{.VENV_BIN_DIR}}/python'

tasks:
  venv:
    desc: "Create a virtual environment and install requirements"
    cmds:
      - python3 -m venv venv
      - '{{.PIP}} install -r requirements.txt'

  run:
    desc: "Run the oauth_session.py script"
    cmds:
      - '{{.PYTHON}} src/oauth_session.py'

  upload:
    desc: "Upload image using Docker and redirect output to a log file"
    cmds:
      - docker run --rm upload-gdrive-image:latest python3 upload_gdrive.py > output.log 2>&1

  all:
    desc: "Set up the venv and run the oauth_session.py script"
    cmds:
      - task: venv
      - task: run