version: "3"

env:
  ENV: testing

dotenv: [".env", "{{.ENV}}/.env", "{{.HOME}}/.env"]

vars:
  VENV_BIN_DIR: venv/bin
  PIP: "{{.VENV_BIN_DIR}}/pip"
  PYTHON: "{{.VENV_BIN_DIR}}/python"

tasks:
  checkenv:
    desc: "Check environment variables"
    dotenv: [".env", "{{.ENV}}/.env", "{{.HOME}}/.env"]
    env:
      KEYNAME: DIFFERENT_VALUE
    cmds:
      - echo "Using $KEYNAME and endpoint $ENDPOINT, from $ENV"

  venv:
    desc: "Create a virtual environment and install requirements"
    cmds:
      - python3 -m venv venv
      - "{{.PIP}} install -r requirements.txt"

  run:
    desc: "Run the oauth_session.py script"
    deps: [venv]
    cmds:
      - "{{.PYTHON}} src/oauth_session.py"

  upload:
    desc: "Upload image using Docker and redirect output to a log file"
    cmds:
      - docker run --rm upload-gdrive-image:latest python3 upload_gdrive.py > output.log 2>&1
  
  copy-upload-file:
    cmds:
      - mkdir -p ./data
      - cp "{{.FILE_DIR}}/{{.FILE_NAME}}" "./data/{{.FILE_NAME}}"

  task-to-be-called:
    cmds:
      - echo "Task to be called"

  another-task:
    cmds:
      - echo "Another task"

  main-task:
    cmds:
      - task: task-to-be-called
      - task: another-task
      - echo "Both done"

  up:
    deps: [task-to-be-called, another-task]
